### ISSUE TITLE
MessageLogger crash while trying to export DB

### ISSUE THREAD

**Issue by Nando600** [Juby210/Aliucord-plugins#46]
When I try to export my DB of keylogger 1.1.3 it just crashes completely leaving this error log 

java.lang.AssertionError
	at io.github.juby210.acplugins.messagelogger.SQLite.exportDatabase(SQLite.java:245)
	at io.github.juby210.acplugins.messagelogger.PluginSettings.onViewCreated$lambda-30$lambda-29(PluginSettings.kt:166)
	at io.github.juby210.acplugins.messagelogger.PluginSettings.$r8$lambda$luhAUUj9IoUpANZqgboXYMOVMhk(Unknown Source:0)
	at io.github.juby210.acplugins.messagelogger.PluginSettings$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7333)
	at android.widget.TextView.performClick(TextView.java:14160)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
	at android.view.View.performClickInternal(View.java:7299)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27773)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by Nick2bad4u** [comment]
Same here. 

![2024-03-30 14_48_42.078.txt](https://github.com/Juby210/Aliucord-plugins/files/14813012/2024-03-30.14_48_42.078.txt)

![2024-03-28 22_53_48.247.txt](https://github.com/Juby210/Aliucord-plugins/files/14813015/2024-03-28.22_53_48.247.txt)

![2024-03-28 22_52_56.285.txt](https://github.com/Juby210/Aliucord-plugins/files/14813016/2024-03-28.22_52_56.285.txt)

![2024-03-26 14_44_25.353.txt](https://github.com/Juby210/Aliucord-plugins/files/14813017/2024-03-26.14_44_25.353.txt)

**Comment by Juby210** [comment]
Should be fixed now.
