### ISSUE TITLE
[PronounDB] Update to api v2

### ISSUE THREAD

**Issue by Lioncat6** [Juby210/Aliucord-plugins#62]
[Aliucord] PronounDB error
com.aliucord.Http$HttpException: 410: Gone (https://pronoundb.org/api/v1/lookup-bulk?platform=discord&ids=1171590584281075748)
APIv1 of PronounDB is no longer in service. Please use APIv2 instead: https://pronoundb.org/wiki/api-docs
  at com.aliucord.Http$Response.assertOk(Http.java, [Aliucord] PronounDB error:575)
  at com.aliucord.Http$Response.stream(Http.java:640)
  at com.aliucord.Http$Response.text(Http.java:580)
  at com.aliucord.Http.simpleGet(Http.java:729)
  at com.aliucord.Http.simpleJsonGet(Http.java:750)
  at io.github.juby210.acplugins.pronoundb.Store.runThread(Store.java:42)
  at io.github.juby210.acplugins.pronoundb.Store.$r8$lambda$jEK1TraRFQ5woQ8upB3ilbsozfs(Unknown Source:0)
  at io.github.juby210.acplugins.pronoundb.Store$$ExternalSyntheticLambda0.run(Unknown Source:0)
  at java.lang.Thread.run(Thread.java:1012)

**Comment by Juby210** [comment]
tbh I don't think there is any point in using that plugin currently. Discord has pronouns built-in now.

**Comment by Lioncat6** [comment]
True... but I like the ability to see pronouns in chat
